### ISSUE TITLE
Chapter 9: Best Practices and Important Data Considerations

### ISSUE THREAD

**Issue by wibeasley** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#138]
- [x] stub in Quarto
- [x] convert Google Docs to markdown (see #33 for some notes)
- [x] download figures (& rename if necessary)
- [x] manually incorporate figures (paths, text, & references)
- [x] split sentences on separate lines
  * pattern: `(?<=[^1])\.[ ]{1,2}(?=\w)`
  * sub: 
    ```
    .
 
    ``` 
    (or with two spaces for indented bullets)
- [x] replace curly quotes with straight quotes `[“”]` and `[‘’]`
- [x] standardize hyphens.  Replace `—` with `--`.  This an em dash replaced by two hyphens (which Pandoc will convert to a dash when rendering the html).
- [x] add spaces are em-dashes.    This follows AP style guide, that's designed for [skinny newspapers](https://www.thepunctuationguide.com/em-dash.html).
  * add space before with pattern `(?<=[^ !-])-{2}(?![+-])` and sub ` --`
  * add space before with pattern `(?<![+-])-{2}(?=[^ >-])` and sub `-- `
- [x] add ` {{< fa lock title="Link requires an N3C Data Enclave account" >}}` (with a space separating the closing `)` and the leading `{{`)  (see #49 for some notes)
- [x] replace `+/-` with `&plusmn;` and [other scientific symbols](https://gist.github.com/webbedfeet/5cdbbb26a880e8fb159b579325d5e841)
- [x] "e.g." and "i.e." should be followed by a comma, and not italicized ([NIH](https://www.ncbi.nlm.nih.gov/books/NBK995/#:~:text=e.g.,and%20follow%20with%20a%20comma.))
- [x] outgoing cross refs (make sure the references to other chapters/sections/figures/tables are resolved)
- [x] incoming cross refs (define anchors for all headers for other chapters/sections to refer to)
- [x] end each figure caption with a period (#116)
- [x] walk-through with author
- [x] a lot of author info is missing --please see what specs they want listed for themselves
- [x] address
    >{Add a short paragraph here about what a protocol is, and if it’s different than the steps outlined above (I assume not, just specialized for RWD analyses)}
- [x] The "Protocol Outline" is not consistent with the entries in the text.  Is it even necessary?  The Chapter's TOC in the right margin will reflect this dynamically
    ![image](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/assets/1372890/6aff82e8-c2a9-4fe6-a022-590a3676e6c9)
- [x] Needs reference at "[cite]"
    - [x] ![image](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/assets/1372890/f74a420f-afb4-468d-b5ca-70bfd0fe3987)
    - [x] ![image](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/assets/1372890/4f85f51f-95a4-4708-8a51-f9c8bda9e07d)
- [x] Incomplete sentence:
    ![image](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/assets/1372890/85e4c2bc-1537-4118-a1b5-e0648c420e53)
- [ ] The GAP text needs a url.  And the sentence need to be completed.
    ![image](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/assets/1372890/7ab5c595-a23a-460e-8fd2-e758c1385380)
- [x] remove "undergoing final edits..." [callout](https://quarto.org/docs/authoring/callouts.html)
* https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/blob/main/chapters/onboarding.md
* https://docs.google.com/document/d/158DkTeYQjEYG9c0zftyIglducWdoKIWT9z1SOLLwpGo/edit

**Comment by wibeasley** [comment]
@hlehmann17, I wrapped up some small issues so we can close the issue and say the chapter is "published".  Can you still provide a url to the GAP forum?

Will you please read the chapter online one last time to confirm there's nothing else you'd like to edit for now.

(cc: @oneilsh)
