### ISSUE TITLE
Chapter 12: (Machine Learning)

### ISSUE THREAD

**Issue by wibeasley** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#189]
- [x] stub in Quarto
- [x] convert Google Docs to markdown (see #33 for some notes)
- [x] download figures (& rename if necessary)
- [x] manually incorporate figures (paths, text, & references)
- [x] split sentences on separate lines
  * pattern: `(?<=[^1])\.[ ]{1,2}(?=\w)`
  * sub: 
    ```
    .
 
    ``` 
    (or with two spaces for indented bullets)
- [x] replace curly quotes with straight quotes `[“”]` and `[‘’]`
- [x] standardize hyphens.  Replace `—` with `--`.  This an em dash replaced by two hyphens (which Pandoc will convert to a dash when rendering the html).
- [x] add spaces are em-dashes.    This follows AP style guide, that's designed for [skinny newspapers](https://www.thepunctuationguide.com/em-dash.html).
  * add space before with pattern `(?<=[^ !-])-{2}(?![+-])` and sub ` --`
  * add space before with pattern `(?<![+-])-{2}(?=[^ >-])` and sub `-- `
- [x] add ` {{< fa lock title="Link requires an N3C Data Enclave account" >}}` (with a space separating the closing `)` and the leading `{{`)  (see #49 for some notes)
- [x] replace `+/-` with `&plusmn;` and [other scientific symbols](https://gist.github.com/webbedfeet/5cdbbb26a880e8fb159b579325d5e841)
- [x] "e.g." and "i.e." should be followed by a comma, and not italicized ([NIH](https://www.ncbi.nlm.nih.gov/books/NBK995/#:~:text=e.g.,and%20follow%20with%20a%20comma.))
- [x] outgoing cross refs (make sure the references to other chapters/sections/figures/tables are resolved)
- [x] incoming cross refs (define anchors for all headers for other chapters/sections to refer to)
- [x] end each figure caption with a period (#116)
- [ ] walk-through with author

**Comment by chrisroederucdenver** [comment]
re download figures and rename....ml has them as image-01-*, I see other have a "fig" prefix. Necessary?

**Comment by chrisroederucdenver** [comment]
What context or regex parser are those regexes used in ?
Vi, sed, VS editor?

**Comment by chrisroederucdenver** [comment]
re: dash vs hyphen
Do you mean to replace intra-word hyphens or inter-word dashes -- like that last one? or both?
(I worked in tech pubs but decades ago. Am I making the distinction correctly?)

**Comment by chrisroederucdenver** [comment]
remaining incomplete out-going references have separate specific issue tickets open

**Comment by wibeasley** [comment]
>What context or regex parser are those regexes used in ? Vi, sed, VS editor?

VS Code

> Do you mean to replace intra-word hyphens or inter-word dashes -- like that last one? or both?

Now I forgot the distinction, but it mattered at the time.  Basically they were inconsistent in the Google Docs, and I standardized them here (and let Pandoc/Quarto convert them where necessary).

**Comment by chrisroederucdenver** [comment]
@justaddcoffee There's that last box to tick off here: walk-through with author.
@wibeasley  ?

**Comment by justaddcoffee** [comment]
sure, glad to walk through this with you all

**Comment by wibeasley** [comment]
@oneilsh and I like this, and don't think a walk-through is still needed.  We'll remove that callout box that says the chapter is still in draft mode.  Thanks for all the work, @justaddcoffee, @chrisroederucdenver, & everyone else!
