### ISSUE TITLE
Chapter 5: Onboarding, Enclave Access, N3C Team Science

### ISSUE THREAD

**Issue by wibeasley** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#45]
- [x] stub in Quarto
- [x] convert Google Docs to markdown (see #33 for some notes)
- [x] download figures (& rename if necessary)
- [x] manually incorporate figures (paths, text, & references)
- [x] split sentences on separate lines
  * pattern: `(?<=[^1])\.[ ]{1,2}(?=\w)`
  * sub: 
    ```
    .
 
    ``` 
    (or with two spaces for indented bullets)
- [x] replace curly quotes with straight quotes `[“”]` and `[‘’]`
- [x] add ` {{< fa lock title="Link requires an N3C Enclave account" >}}` (with a space separating the closing `)` and the leading `{{`)  (see #49 for some notes)
- [x] replace `+/-` with `&plusmn;` and [other scientific symbols](https://gist.github.com/webbedfeet/5cdbbb26a880e8fb159b579325d5e841)
- [x] outgoing cross refs (make sure the references to other chapters/sections/figures/tables are resolved)
- [x] incoming cross refs (define anchors for all headers for other chapters/sections to refer to)
- [x] end each figure caption with a period (#116)
- [x] walk-through with author
- [x] missing four figures (that were embedded in the Google Doc, but were missing from the stand-alone pngs)
- [x] Is there supposed to be a heading and transition here?
    ![image](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/assets/1372890/b8a13993-5c29-449c-8f82-2e38566d89d1)
- [x] This section is pretty choppy.  Can you think of a way to make it flow better?
    ![image](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/assets/1372890/e286ea50-2192-4661-9884-90277e056f81)
- [x] fig-onboarding-030-login.png needs the red ellipse around the first dropdown box.
   (never mind --remove the red circle)
- [x] Is there a sentence or two you can use to open 9.5?
    ![image](https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/assets/1372890/5a4db5c6-0ec2-4485-b2ad-954b0a4c4bf5)
- [x] remove "undergoing final edits..." [callout](https://quarto.org/docs/authoring/callouts.html)

* https://github.com/National-COVID-Cohort-Collaborative/guide-to-n3c-v1/blob/main/chapters/onboarding.md
* https://docs.google.com/document/d/163tYeG1ON9itSLneIlsS_QQeQaca-f6zUhEkvoggu7k/edit
