### ISSUE TITLE
Chapter 3: Data Life Cycle - From Patients to N3C Researchers

### ISSUE THREAD

**Issue by wibeasley** [National-COVID-Cohort-Collaborative/guide-to-n3c-v1#98]
- [x] source is complete
- [x] convert Google Docs to markdown (see #33 for some notes)
- [x] download figures (& rename if necessary)
- [x] manually incorporate figures (paths, text, & references)
- [x] split sentences on separate lines
  * pattern: `(?<=[^1])\.[ ]{1,2}(?=\w)`
  * sub: 
    ```
    .
 
    ``` 
    (or with two spaces for indented bullets)
- [x] replace curly quotes with straight quotes `[“”]` and `[‘’]`
- [x] add ` {{< fa lock title="Link requires an N3C Enclave account" >}}` (with a space separating the closing `)` and the leading `{{`)  (see #49 for some notes)
- [x] replace `+/-` with `&plusmn;` and [other scientific symbols](https://gist.github.com/webbedfeet/5cdbbb26a880e8fb159b579325d5e841)
- [x] outgoing cross refs (make sure the references to other chapters/sections/figures/tables are resolved)
- [x] incoming cross refs (define anchors for all headers for other chapters/sections to refer to)
- [x] end each figure caption with a period (#116)
- [x] change "lifecycle" to "life cycle" ([per this Slack discussion](https://cd2h.slack.com/archives/C03J61BJA3W/p1682551018581679)) and the filename/cross-references from "lifecycle" to "cycle"
- [x] There are some paragraphs you might want to break into two.  Web pages/sites tend to be narrower than a piece of paper.  So some of the paragraph extend from the top to beyond the bottom of a laptop screen.  Nothing bad or wrong.  You just might want a visual break in a few more places.
- [x] Stephanie & Tanner should use the same organization abbreviation
- [x] the figure captions need some more detail, and some captions aren't easily distinguishable
- [x] the resolution of the figures is very low.  @oneilsh captured some great screenshots.  Can you get tips from him?  In short, use a big monitor and maximize the browser.
- [x] What is this supposed to connect to? `*Clinical Data contains data enhancements from data partners which includes long COVID clinic visits, ADT transactions, O2 devices, NLP, and SDoH datasets.`
- [x] I changed "O2" to "oxygen" --is this ok?
- [x] something is off/unbalanced with this double-quotation and the sentence maybe.
    ![image](https://user-images.githubusercontent.com/1372890/235026524-f46b17e2-8417-4f23-affc-36ab59b9e996.png)
- [x] I changed the bullets to numbers for the "grouped into 7 categories..." --is this ok?
- [x] I created a numbered list for the "The N3C Data ingestion pipeline..." --is this ok?
- [x] I created a numbered list for the "unit-harmonization pipeline..." --is this ok?
- [x] walk-through with author
- [ ] remove "undergoing final edits..." [callout](https://quarto.org/docs/authoring/callouts.html)

* https://docs.google.com/document/d/1EE4nUlYuHAwSCuN0BjRwKAeq27MOAr9uapRGFzSAzik/edit
* https://national-covid-cohort-collaborative.github.io/guide-to-n3c-v1/chapters/cycle.html

**Comment by stephanieshong** [comment]
@wibeasley  - I added one more higher res image file for you to merge.
